name: Release and Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple
          package-name: team5_model

  build-and-push:
    needs: release-please
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get version
      id: get_version
      run: |
        if [[ "${{ needs.release-please.outputs.release_created }}" == "true" ]]; then
          echo "version=${{ needs.release-please.outputs.tag_name }}" >> $GITHUB_OUTPUT
        elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo "version=$(echo ${GITHUB_HEAD_REF} | sed 's/[^a-zA-Z0-9]/-/g')" >> $GITHUB_OUTPUT
        else
          echo "version=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT
        fi

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/Dockerfile.base
        push: true
        tags: |
          ghiret/hackathon_bio:model_image-${{ steps.get_version.outputs.version }}
          ghiret/hackathon_bio:model_image-latest
        build-args: |
          BUILDKIT_INLINE_CACHE=1
        cache-from: type=registry,ref=ghiret/hackathon_bio:model_image-buildcache
        cache-to: type=registry,ref=ghiret/hackathon_bio:model_image-buildcache,mode=max

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/Dockerfile.inference
        push: true
        tags: |
          ghiret/hackathon_bio:inference_image-${{ steps.get_version.outputs.version }}
        build-args: |
          BUILDKIT_INLINE_CACHE=1
        cache-from: type=registry,ref=ghiret/hackathon_bio:inference_image-buildcache
        cache-to: type=registry,ref=ghiret/hackathon_bio:inference_image-buildcache,mode=max
